# Generated by Django 4.2.3 on 2023-07-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_stock',
            field=models.IntegerField(null=True),
        ),
    ]
