# Generated by Django 4.2.7 on 2023-11-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_quantity_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
