# Generated by Django 4.2.7 on 2023-11-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.distributor'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
