# Generated by Django 4.2.7 on 2023-11-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_distributor_alter_distributor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.distributor'),
        ),
    ]
