# Generated by Django 4.2.3 on 2023-07-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_name_pr_order_quantity_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
