# Generated by Django 4.2.7 on 2023-11-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cansellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
