# Generated by Django 4.2.7 on 2023-11-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_is_cansellation_order_is_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_status',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
