# Generated by Django 4.2.7 on 2023-11-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_is_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_status',
            field=models.IntegerField(default=0),
        ),
    ]
